Feature: Work
  As a visitor
  I should see the Isotope11 portfolio
  In order to learn more about the company

  Scenario: The page exists
    When I am on the work page
    Then I should see "Work"
    And I should see "Financial Services"
    And I should see "AIUA"
    And I should see "Sportgraphics"
    And I should see "Financial"
    And I should see "Financial Services"
    And I should see "Government"
    And I should see "AIDT"
    And I should see "Retail"
    And I should see "Deep South Fibers"
    And I should see "Creative Catering"
    And I should see "In the Making"
    And I should see "Social Media"
    And I should see "aColleague"
    And I should see "LuvNotes"
    And I should see "Miscellaneous"
    And I should see "Maralyn Wilson Gallery"
    And I should see "The Political Inquirer"

  Scenario: The images exist
    When I am on the work page
    Then I should see the alt text "Insight Card Services"
    And I should see the alt text "AIUA"
    And I should see the alt text "Sportgraphics"
    And I should see the alt text "Insight thumb"
    And I should see the alt text "AIDT thumb"
    And I should see the alt text "Deep South Fibers thumb"
    And I should see the alt text "Creative Catering thumb"
    And I should see the alt text "Shop ITM thumb"
    And I should see the alt text "AColleague thumb"
    And I should see the alt text "LuvNotes thumb"
    And I should see the alt text "Maralyn Wilson Gallery thumb"
    And I should see the alt text "AIUA thumb"
    And I should see the alt text "The Political Inquirer thumb"
    And I should see the alt text "Sportgraphics thumb"

  Scenario: The links work
    Given I am on the work page
    When I follow "Insight Card Services"
    Then I should see "Financial Services"
    When I follow "Back to Work"
    And I follow "AIUA"
    Then I should see "We integrated with Google Maps"
    When I follow "Back to Work"
    And I follow "Sportgraphics"
    Then I should see "Sportgraphics has photographed most of the major regattas since 1986"
    When I follow "Back to Work"
    And I follow "Insight thumb"
    Then I should see "Financial Services is a leading provider of financial solutions"
    When I follow "Back to Work"
    And I follow "AIDT thumb"
    Then I should see "AIDT was established by the Alabama State Legislature"
    When I follow "Back to Work"
    And I follow "Deep South Fibers thumb"
    Then I should see "Deep South Fibers, the innovative source for ‘all things knitting,’"
    When I follow "Back to Work"
    And I follow "Creative Catering thumb"
    Then I should see "Creative Catering has a distinct focus on creative menus"
    When I follow "Back to Work"
    And I follow "Shop ITM thumb"
    Then I should see "ShopITM.com is a 5000+ item online store specializing in knitting items"
    When I follow "Back to Work"
    And I follow "AColleague thumb"
    Then I should see "aColleague.com does something outrageous"
    When I follow "Back to Work"
    And I follow "LuvNotes thumb"
    Then I should see "Welcome to Luvnotes, the all-occasion card application"
    When I follow "Back to Work"
    And I follow "Maralyn Wilson Gallery thumb"
    Then I should see "For 35 years the Maralyn Wilson Gallery has brought outstanding American crafts"
    When I follow "Back to Work"
    And I follow "AIUA thumb"
    Then I should see "We integrated with Google Maps and Yahoo!'s geolocating service"
    When I follow "Back to Work"
    And I follow "The Political Inquirer thumb"
    Then I should see "The Political Inquirer is devoted to the free exchange of ideas through writing"
    When I follow "Back to Work"
    And I follow "Sportgraphics thumb"
    Then I should see "Sportgraphics has photographed most of the major regattas since 1986"

